test = {'name': 'b',
 'points': 0.1,
 'suites': [{'cases': [{'code': '>>> tomato = Item("tomato", 4, "vegetable")\n'
                                '\n'
                                '>>> kale = Item("kale", 1, "vegetable")\n'
                                '\n'
                                '>>> apple = Item("apple", 2, "fruit")\n'
                                '\n'
                                '>>> chicken = Item("chicken", 3, "meat")\n'
                                '\n'
                                '>>> oreos = Item("oreos", 6, "junk_food")\n'
                                '\n'
                                '>>> stuff = GroceryList([tomato, kale, apple, '
                                'chicken, oreos])\n'
                                '\n'
                                '>>> stuff.items\n'
                                '[tomato, kale, apple, chicken, oreos]\n'
                                '\n'
                                '>>> stuff.buy_item("chicken")\n'
                                '\n'
                                '>>> stuff.items\n'
                                '[tomato, kale, apple, oreos]\n'
                                '\n'
                                '>>> stuff.buy_item("kale")\n'
                                '\n'
                                '>>> stuff.items\n'
                                '[tomato, apple, oreos]\n'
                                '\n'
                                '>>> stuff.buy_item("tomato")\n'
                                '\n'
                                '>>> stuff.items\n'
                                '[apple, oreos]\n'
                                '\n'
                                '>>> stuff.buy_item("apple")\n'
                                '\n'
                                '>>> stuff.items\n'
                                '[oreos]\n'
                                '\n'
                                '>>> stuff.buy_item("oreos")\n'
                                '\n'
                                '>>> stuff.items\n'
                                '[]\n'}],
             'scored': True,
             'setup': '>>> from q5 import *',
             'type': 'doctest'},
            {'cases': [{'code': '>>> broccoli = Item("broccoli", 4, '
                                '"vegetable")\n'
                                '\n'
                                '>>> kale = Item("kale", 1, "vegetable")\n'
                                '\n'
                                '>>> apple = Item("apple", 2, "fruit")\n'
                                '\n'
                                '>>> pork = Item("pork", 3, "meat")\n'
                                '\n'
                                '>>> oreos = Item("oreos", 6, "junk_food")\n'
                                '\n'
                                '>>> stuff = GroceryList([oreos, apple, kale, '
                                'broccoli, pork])\n'
                                '\n'
                                '>>> stuff.items\n'
                                '[oreos, apple, kale, broccoli, pork]\n'
                                '\n'
                                '>>> stuff.buy_item("pork")\n'
                                '\n'
                                '>>> stuff.items\n'
                                '[oreos, apple, kale, broccoli]\n'
                                '\n'
                                '>>> stuff.buy_item("kale")\n'
                                '\n'
                                '>>> stuff.items\n'
                                '[oreos, apple, broccoli]\n'
                                '\n'
                                '>>> stuff.buy_item("broccoli")\n'
                                '\n'
                                '>>> stuff.items\n'
                                '[oreos, apple]\n'
                                '\n'
                                '>>> stuff.buy_item("apple")\n'
                                '\n'
                                '>>> stuff.items\n'
                                '[oreos]\n'
                                '\n'
                                '>>> stuff.buy_item("oreos")\n'
                                '\n'
                                '>>> stuff.items\n'
                                '[]\n'}],
             'scored': True,
             'setup': '>>> from q5 import *',
             'type': 'doctest'}]}