test = {'name': 'q3',
 'points': 1,
 'suites': [{'cases': [{'code': '>>> t1 = Tree(1, [Tree(2, [Tree(3, '
                                '[Tree(4)])]), Tree(5)])\n'
                                '\n'
                                '>>> print(t1)\n'
                                '1\n'
                                '    2\n'
                                '        3\n'
                                '            4\n'
                                '    5\n'
                                '\n'
                                '>>> same_length(t1, 2)\n'
                                '\n'
                                '>>> print(t1)\n'
                                '1\n'
                                '    2\n'
                                '        3\n'
                                '    5\n'
                                '        hello\n'
                                '\n'
                                '>>> t2 = Tree(4, [Tree(5, [Tree(6), '
                                'Tree(7)]), Tree(10), Tree(15, [Tree(16, '
                                '[Tree(17, [Tree(18, [Tree(19)])])])])])\n'
                                '\n'
                                '>>> same_length(t2, 3)\n'
                                '\n'
                                '>>> print(t2)\n'
                                '4\n'
                                '    5\n'
                                '        6\n'
                                '            hello\n'
                                '        7\n'
                                '            hello\n'
                                '    10\n'
                                '        hello\n'
                                '            hello\n'
                                '    15\n'
                                '        16\n'
                                '            17\n'
                                '\n'
                                '>>> t1 = Tree(1, [Tree(2, [Tree(3)]), Tree(5, '
                                '[Tree("hello")])])\n'
                                '\n'
                                '>>> print(t1)\n'
                                '1\n'
                                '    2\n'
                                '        3\n'
                                '    5\n'
                                '        hello\n'
                                '\n'
                                '>>> shortest_no_hello(t1)\n'
                                '[1, 5]\n'
                                '\n'
                                '>>> t2 = Tree(4, [Tree(5, [Tree(6, '
                                '[Tree("hello")]), Tree(7, [Tree("hello")])]), '
                                'Tree(10, [Tree("hello", [Tree("hello")])]), '
                                'Tree(15, [Tree(16, [Tree(17)])])])\n'
                                '\n'
                                '>>> print(t2)\n'
                                '4\n'
                                '    5\n'
                                '        6\n'
                                '            hello\n'
                                '        7\n'
                                '            hello\n'
                                '    10\n'
                                '        hello\n'
                                '            hello\n'
                                '    15\n'
                                '        16\n'
                                '            17\n'
                                '\n'
                                '>>> shortest_no_hello(t2)\n'
                                '[4, 10]\n'
                                '\n'
                                '>>> t = Tree(3, [Tree(2, [Tree(5)]), '
                                'Tree(4)])\n'
                                '\n'
                                '>>> t.label\n'
                                '3\n'
                                '\n'
                                '>>> t.branches[0].label\n'
                                '2\n'
                                '\n'
                                '>>> t.branches[1].is_leaf()\n'
                                'True\n'}],
             'scored': True,
             'setup': '>>> from q3 import *',
             'type': 'doctest'}]}